CREATE DATABASE BOOK
USE [Book]
GO
/****** Object:  Table [dbo].[BOOK]    Script Date: 12/5/2022 2:43:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[BOOK_ID] [varchar](255) NULL,
	[BOOK_NAME] [varchar](255) NOT NULL,
	[AUTHOR] [varchar](255) NULL,
	[AVAILABLE_COPIES] [int] NULL,
	[TOTAL_COPIES] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[BOOKAVAILABLE]    Script Date: 12/5/2022 2:43:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create PROCEDURE [dbo].[BOOKAVAILABLE]
(
@BookId varchar(255)
)
AS
BEGIN
	IF EXISTS( select ID from BOOK where BOOK_ID=@BookId AND AVAILABLE_COPIES>0)
		BEGIN
		 SELECT 1 AS EXIST
		END
	ELSE
		BEGIN
		SELECT 0 AS EXIST
		END
END
GO
/****** Object:  StoredProcedure [dbo].[GETBOOKS]    Script Date: 12/5/2022 2:43:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

Create PROCEDURE [dbo].[GETBOOKS]
AS
BEGIN
SELECT 
	ID,BOOK_ID,BOOK_NAME,AUTHOR,AVAILABLE_COPIES,TOTAL_COPIES 
FROM BOOK
END
GO
